#!/bin/bash -l
#$ -cwd
#$ -P wax-dk
#$ -pe omp 1
#$ -l mem_per_core=8G
#$ -l h_rt=06:00:00
# -l scratch_free=200G

echo "=========================================================="
Start_Time=$(date +"%s")
echo "Starting on : $(date)"
echo "Running on node   : $(hostname)"
echo "Current job ID    : $JOB_ID"
echo "Current job name  : $JOB_NAME"
echo "Task index number : $TASK_ID"
echo "=========================================================="

set -eu
SESSION=$1
TOP25FILE=$2
RVERSION=$3

module load "R/${RVERSION}"

Rscript ./download_ucsc_pdf.R --session "${SESSION}" --input_file ${TOP25FILE}

End_Time=$(date +"%s")
diff=$(($End_Time-$Start_Time))
echo "$(($diff / 3600)) hours, $((($diff / 60) % 60)) minutes and $(($diff % 60)) seconds elapsed."
echo "=========================================================="
echo "IAMOK"
